* Weizman - Into Forensis (a critical forensic practice)
** Glossary  / quotes :
*** /Prospopeia/ - the mediated speech of inamimate objects.
*** /Forensis/ - pertaining to the the forum. Forensics as a political practice
*** /evidentia in narratione/ "in which truth requires not merely to be told but to a certain extent obtruded"
*** forensic anthropologist - "bones make great witnesses"
** Ideas
*** Forensic Architecture came out a the "problematization of contemporary forensic practices"
Make forensics a counter-hegemonic practice
*** Political plastics and Forensic aethestics 
*** Buildings structure and condition rather than simply frame human action, they actively sometimes violently shape incidents and events
*** Cracks are sensors and agents, they are material events. Cracks on a skull hit by a bullet travel faster than the bullet

*** In Bangladesh factory case - “ a focus on the material condition of Both the workers and the building is required”
*** Field Causality : 
To establish field causality for violence an injustice is to articulate the material basis for the imperative to dismantle or fundamentally reconfigure a political field, as opposed to the standard tendency of International justice to isolate a few culpable individuals while leaving the social and economic hierarchies of society intact.\
*** Science and politics :
Unlike science, politics is not driven by a desire for a well-constructed truth, and unlike law it does not seek to render judgment on past events from the vantage point of the present order: rather, it is driven by a desire to change the way things are. 
An important component in our ability to respond to political challenges is the capacity of forensis to move beyond detecting, calculating, processing, and presenting acts of injustice. Achieving a heightened aesthetic state of material sensitivity, tuned to weak signals, must be enhanced by a sensitivity to the materiality of politics: this entails an appreciation that whether you are a building, a territory, a pixel, or a person, to detect is to transform, and to be transformed is to feel pain.
